shopware:
    admin_worker:
        enable_admin_worker: false
    auto_update:
        enabled: false
    increment:
        user_activity:
            type: 'array'
        message_queue:
            type: 'array'
    cdn:
        url: '%env(CDN_URL)%'
